name: do_you_know_hearthstone
description: "A Hearthstone guessing game."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.2
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/csv/

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/fonts/GeneralSans-ExtralightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-LightItalic.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-Regular.otf
          style: normal
        - asset: assets/fonts/GeneralSans-Italic.otf
          style: italic
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/GeneralSans-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/GeneralSans-BoldItalic.otf
          weight: 700
          style: italic
